@extends('layouts.inventory-layout')

@section('title', 'Prottasha | Inventory')


@section('content')

 <div class="container">
<div class="row header" style="text-align:center;color:green">
 <h1>Purchase List</h1>
  </div>
 <table id="myTable" class="table table-striped" >
                                                                                                                                                                                                                                                               <thead>
                                                                                                                                                                                                                                                             <tr>
                                                                                                                                                                                                                                                              <th>Product ID</th>
                                                                                                                                                                                                                                                             <th>Product Title</th>
                                                                                                                                                                                                                                                          <th>Purchase Quanity</th>
                                                                                                                                                                                                                                                        <th>Buying Price</th>
                                                                                                                                                                                                                                                      <th>Total Price</th>
                                                                                                                                                                                                                                                       <th>Selling Price</th>
                                                                                                                                                                                                                                                  <th>Purchase Date</th>
                                                                                                                                                                                                                                                <th>Purchase By</th>
                                                                                                                                                                                                                                                                 <th></th>
                                                                                                                                                                                                                                                             </tr>
                                                                                           </thead>
                                                                                                                                                                                                                                                                                                                                                          <tbody>

                                                                                                                                                                                                                                                                                                                                                              @foreach($purchases as $purchase)

                                                                                                                                                                                                                                                                                                                                                                  <tr>
                                                                                                                                                                                                                                                                                                                                                                      <td class="txt-dark">{{$purchase->p_id}}</td>
                                                                                                                                                                                                                                                                                                                                                                      <td class="txt-dark">{{$purchase->product_name}}</td>
                                                                                                                                                                                                                                                                                                                                                                      <td class="txt-dark">{{$purchase->added_quantity}}</td>
                                                                                                                                                                                                                                                                                                                                                                      <td class="txt-dark">{{$purchase->buying_price}}</td>
                                                                                                                                                                                                                                                                                                                                                                      <td class="txt-dark">{{$purchase->added_quantity * $purchase->buying_price}}</td>
                                                                                                                                                                                                                                                                                                                                                                      <td class="txt-dark">{{$purchase->selling_price}}</td>
                                                                                                                                                                                                                                                                                                                                                                      <td class="txt-dark">{{$purchase->created_at}}</td>
                                                                                                                                                                                                                                                                                                                                                                      <td class="txt-dark"><a href="/user/details/{{$purchase->added_by}}">{{$purchase->added_name}}</a></td>
                                                                                                                                                                                                                                                                                                                                                                      <td><a href="#" class="btn btn-primary a-btn-slide-text">
                                                                                                                                                                                                                                                                                                                                                                              <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                                                                                                                                                                                                                                                                                                                                                              <span><strong>Edit</strong></span>
                                                                                                                                                                                                                                                                                                                                                                          </a></td>

                                                                                                                                                                                                                                                                                                                                                                  </tr>


                                                                                                                                                                                                                                                                                                                                                              @endforeach

                                                                                                                                                                                                                                                                                                                                                          </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
@endsection
@section('scripts')
 <script>
     $(document).ready(function(){
        $('#myTable').dataTable();
    });
    </script>
    @endsection

